// Generated by designlang v7.0.0
// Source: https://www.tebra.com/
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFFFF8D6E);
  static const Color actionSecondary = Color(0xFF004952);
  static const Color surfaceDefault = Color(0xFFFFFFFF);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 15;
  static const double spacingS2 = 30;
  static const double spacingS3 = 35;
  static const double spacingS4 = 40;
  static const double spacingS5 = 47;
  static const double spacingS6 = 52;
  static const double spacingS7 = 56;
  static const double spacingS8 = 64;
  static const double spacingS9 = 78;
  static const double spacingS10 = 103;
  static const double spacingS11 = 107;
  static const double spacingS12 = 116;
  static const double spacingS13 = 136;
  static const double spacingS14 = 145;
  static const double spacingS15 = 180;
  static const double spacingS16 = 184;
  static const double spacingS17 = 199;
  static const double spacingS18 = 268;
  static const double spacingS19 = 308;
  static const double spacingS20 = 474;
  static const double radiusR0 = 1;
  static const double radiusR1 = 4;
  static const double radiusR2 = 7;
  static const double radiusR3 = 10;
  static const double radiusR4 = 16;
  static const double radiusR5 = 20;
  static const double radiusR6 = 24;
  static const double radiusR7 = 30;
  static const double radiusR8 = 50;
  static const double radiusR9 = 57;
  static const double radiusR10 = 60;
  static const double radiusR11 = 100;

  // Primitive palette
  static const Color brandPrimary = Color(0xFFFF8D6E);
  static const Color brandSecondary = Color(0xFF004952);
  static const Color neutralN100 = Color(0xFF000000);
  static const Color neutralN200 = Color(0xFF232323);
  static const Color neutralN300 = Color(0xFFFFFFFF);
  static const Color neutralN400 = Color(0xFF555555);
  static const Color neutralN500 = Color(0xFFDCDCDC);
  static const Color neutralN600 = Color(0xFF8CA7A2);
  static const Color neutralN700 = Color(0xFF696969);
  static const Color neutralN800 = Color(0xFF000A0C);
  static const Color neutralN900 = Color(0xFFC5D6D7);
  static const Color neutralN1000 = Color(0xFF767676);
  static const Color neutralN1100 = Color(0xFFBBBBBB);
  static const Color backgroundBg0 = Color(0xFFFFFFFF);
  static const Color backgroundBg1 = Color(0xFF004952);
  static const Color backgroundBg2 = Color(0xFFF5F8F8);
  static const Color backgroundBg3 = Color(0xFF8CA7A2);
  static const Color backgroundBg4 = Color(0xFFEBF0EF);
  static const Color backgroundBg5 = Color(0xFFF6F8F8);
  static const Color backgroundBg6 = Color(0xFFF8F3EB);
  static const Color backgroundBg7 = Color(0xFFFDFBFB);
  static const Color backgroundBg8 = Color(0xFFFF8D6E);
  static const Color backgroundBg9 = Color(0xFFEFEFEF);
  static const Color backgroundBg10 = Color(0xFF000000);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF003A43);
  static const Color textText2 = Color(0xFF232323);
  static const Color textText3 = Color(0xFF004952);
  static const Color textText4 = Color(0xFFF8F3EB);
  static const Color textText5 = Color(0xFF2B2B2B);
  static const Color textText6 = Color(0xFFFFFFFF);
  static const Color textText7 = Color(0xFF555555);
  static const Color textText8 = Color(0xFF3860BE);
  static const Color textText9 = Color(0xFF696969);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
