// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://www.tebra.com/
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xFF8D6E)
  static let actionSecondary = Color(hex: 0x004952)
  static let surfaceDefault = Color(hex: 0xFFFFFF)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 15
  static let spacingS2: CGFloat = 30
  static let spacingS3: CGFloat = 35
  static let spacingS4: CGFloat = 40
  static let spacingS5: CGFloat = 47
  static let spacingS6: CGFloat = 52
  static let spacingS7: CGFloat = 56
  static let spacingS8: CGFloat = 64
  static let spacingS9: CGFloat = 78
  static let spacingS10: CGFloat = 103
  static let spacingS11: CGFloat = 107
  static let spacingS12: CGFloat = 116
  static let spacingS13: CGFloat = 136
  static let spacingS14: CGFloat = 145
  static let spacingS15: CGFloat = 180
  static let spacingS16: CGFloat = 184
  static let spacingS17: CGFloat = 199
  static let spacingS18: CGFloat = 268
  static let spacingS19: CGFloat = 308
  static let spacingS20: CGFloat = 474

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 1
  static let radiusR1: CGFloat = 4
  static let radiusR2: CGFloat = 7
  static let radiusR3: CGFloat = 10
  static let radiusR4: CGFloat = 16
  static let radiusR5: CGFloat = 20
  static let radiusR6: CGFloat = 24
  static let radiusR7: CGFloat = 30
  static let radiusR8: CGFloat = 50
  static let radiusR9: CGFloat = 57
  static let radiusR10: CGFloat = 60
  static let radiusR11: CGFloat = 100
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xFF8D6E)
  static let brandSecondary = Color(hex: 0x004952)
  static let neutralN100 = Color(hex: 0x000000)
  static let neutralN200 = Color(hex: 0x232323)
  static let neutralN300 = Color(hex: 0xFFFFFF)
  static let neutralN400 = Color(hex: 0x555555)
  static let neutralN500 = Color(hex: 0xDCDCDC)
  static let neutralN600 = Color(hex: 0x8CA7A2)
  static let neutralN700 = Color(hex: 0x696969)
  static let neutralN800 = Color(hex: 0x000A0C)
  static let neutralN900 = Color(hex: 0xC5D6D7)
  static let neutralN1000 = Color(hex: 0x767676)
  static let neutralN1100 = Color(hex: 0xBBBBBB)
  static let backgroundBg0 = Color(hex: 0xFFFFFF)
  static let backgroundBg1 = Color(hex: 0x004952)
  static let backgroundBg2 = Color(hex: 0xF5F8F8)
  static let backgroundBg3 = Color(hex: 0x8CA7A2)
  static let backgroundBg4 = Color(hex: 0xEBF0EF)
  static let backgroundBg5 = Color(hex: 0xF6F8F8)
  static let backgroundBg6 = Color(hex: 0xF8F3EB)
  static let backgroundBg7 = Color(hex: 0xFDFBFB)
  static let backgroundBg8 = Color(hex: 0xFF8D6E)
  static let backgroundBg9 = Color(hex: 0xEFEFEF)
  static let backgroundBg10 = Color(hex: 0x000000)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x003A43)
  static let textText2 = Color(hex: 0x232323)
  static let textText3 = Color(hex: 0x004952)
  static let textText4 = Color(hex: 0xF8F3EB)
  static let textText5 = Color(hex: 0x2B2B2B)
  static let textText6 = Color(hex: 0xFFFFFF)
  static let textText7 = Color(hex: 0x555555)
  static let textText8 = Color(hex: 0x3860BE)
  static let textText9 = Color(hex: 0x696969)
}

// typography.body: family=__AkkuratLL_8dc0fd size=68px weight=400 lineHeight=81.6px
