// Generated by designlang v7.0.0
// Source: https://www.tebra.com/
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFFFF8D6E)
    val ActionSecondary = Color(0xFF004952)
    val SurfaceDefault = Color(0xFFFFFFFF)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFFFF8D6E)
    val BrandSecondary = Color(0xFF004952)
    val NeutralN100 = Color(0xFF000000)
    val NeutralN200 = Color(0xFF232323)
    val NeutralN300 = Color(0xFFFFFFFF)
    val NeutralN400 = Color(0xFF555555)
    val NeutralN500 = Color(0xFFDCDCDC)
    val NeutralN600 = Color(0xFF8CA7A2)
    val NeutralN700 = Color(0xFF696969)
    val NeutralN800 = Color(0xFF000A0C)
    val NeutralN900 = Color(0xFFC5D6D7)
    val NeutralN1000 = Color(0xFF767676)
    val NeutralN1100 = Color(0xFFBBBBBB)
    val BackgroundBg0 = Color(0xFFFFFFFF)
    val BackgroundBg1 = Color(0xFF004952)
    val BackgroundBg2 = Color(0xFFF5F8F8)
    val BackgroundBg3 = Color(0xFF8CA7A2)
    val BackgroundBg4 = Color(0xFFEBF0EF)
    val BackgroundBg5 = Color(0xFFF6F8F8)
    val BackgroundBg6 = Color(0xFFF8F3EB)
    val BackgroundBg7 = Color(0xFFFDFBFB)
    val BackgroundBg8 = Color(0xFFFF8D6E)
    val BackgroundBg9 = Color(0xFFEFEFEF)
    val BackgroundBg10 = Color(0xFF000000)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF003A43)
    val TextText2 = Color(0xFF232323)
    val TextText3 = Color(0xFF004952)
    val TextText4 = Color(0xFFF8F3EB)
    val TextText5 = Color(0xFF2B2B2B)
    val TextText6 = Color(0xFFFFFFFF)
    val TextText7 = Color(0xFF555555)
    val TextText8 = Color(0xFF3860BE)
    val TextText9 = Color(0xFF696969)
    val SpacingS0 = 1.dp
    val SpacingS1 = 15.dp
    val SpacingS2 = 30.dp
    val SpacingS3 = 35.dp
    val SpacingS4 = 40.dp
    val SpacingS5 = 47.dp
    val SpacingS6 = 52.dp
    val SpacingS7 = 56.dp
    val SpacingS8 = 64.dp
    val SpacingS9 = 78.dp
    val SpacingS10 = 103.dp
    val SpacingS11 = 107.dp
    val SpacingS12 = 116.dp
    val SpacingS13 = 136.dp
    val SpacingS14 = 145.dp
    val SpacingS15 = 180.dp
    val SpacingS16 = 184.dp
    val SpacingS17 = 199.dp
    val SpacingS18 = 268.dp
    val SpacingS19 = 308.dp
    val SpacingS20 = 474.dp
    val RadiusR0 = 1.dp
    val RadiusR1 = 4.dp
    val RadiusR2 = 7.dp
    val RadiusR3 = 10.dp
    val RadiusR4 = 16.dp
    val RadiusR5 = 20.dp
    val RadiusR6 = 24.dp
    val RadiusR7 = 30.dp
    val RadiusR8 = 50.dp
    val RadiusR9 = 57.dp
    val RadiusR10 = 60.dp
    val RadiusR11 = 100.dp
}
